CREATE TABLE IF NOT EXISTS abxy AS (SELECT * FROM read_csv('abxy.csv'));

CREATE VIEW IF NOT EXISTS a1b0 AS (SELECT X, Y FROM abxy WHERE A=1 AND B=0);
CREATE VIEW IF NOT EXISTS a0b1 AS (SELECT X, Y FROM abxy WHERE A=0 AND B=1);
CREATE VIEW IF NOT EXISTS a1b1 AS (SELECT X, Y FROM abxy WHERE A=1 AND B=1);
